"""Where verdicts and feedback go, and what is deliberately left out.

The project's largest gap is not code, it is data: the false-positive rate
is measured only against press photography, calibration only against easy
images, and the video weights were never fitted at all. All three want the
same thing — real images, with someone saying whether the answer was right.

`POST /api/feedback` has existed since Phase 2 and already collects exactly
that. It wrote to a JSONL file nobody read, and on an ephemeral filesystem
that file is erased every time the service sleeps. This module is what makes
those answers survive.

--------------------------------------------------------------- what is kept

    when, what kind of file, how big, what the model said, how sure it was,
    which model version said it, how long it took, and whether a human
    disagreed.

--------------------------------------------------- what is deliberately not

    **Media.** Never. Not the image, not a thumbnail, not a hash of one.
    **Filenames.** "passport.jpg" and "me_and_priya.jpg" are personal in a
      way file size is not. Only the extension survives.
    **IP addresses.** The rate limiter needs one in memory for sixty
      seconds; writing it down turns analytics into tracking.
    **Anything tying a row to a person.** `scan_id` is generated by the
      browser per scan and links a verdict to its feedback. It identifies
      a scan, not a human.

------------------------------------------------------------------ behaviour

No `DATABASE_URL` means no database: feedback appends to JSONL exactly as
before and analyses are not recorded. Local development needs nothing
installed. `DS_ANALYTICS=0` disables all persistence, including that JSONL
fallback.

**A failure here never fails a request.** Analytics that can take the
product down is worse than no analytics, so every write is best-effort, runs
off the request thread, and swallows its own errors after logging them.
"""
import json
import logging
import os
import threading
from datetime import datetime, timezone

from config import CFG

log = logging.getLogger("deepshield")

__all__ = ["record_analysis", "record_feedback", "summary", "backend_name",
           "ensure_schema"]

_schema_ready = False
_lock = threading.Lock()


# --------------------------------------------------------------- the backend

def _psycopg():
    """The driver, or None. Optional on purpose — see requirements.txt."""
    try:
        import psycopg
        return psycopg
    except ImportError:
        return None


def enabled() -> bool:
    return bool(CFG.ANALYTICS and CFG.DATABASE_URL and _psycopg())


def backend_name() -> str:
    if not CFG.ANALYTICS:
        return "off"
    if not CFG.DATABASE_URL:
        return "file"
    return "postgres" if _psycopg() else "file (psycopg not installed)"


def _connect():
    psycopg = _psycopg()
    return psycopg.connect(CFG.DATABASE_URL,
                           connect_timeout=CFG.DB_TIMEOUT_SECONDS)


SCHEMA = """
CREATE TABLE IF NOT EXISTS analyses (
    id            BIGSERIAL PRIMARY KEY,
    at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    scan_id       TEXT,
    file_type     TEXT,
    file_ext      TEXT,
    file_bytes    BIGINT,
    prediction    TEXT,
    confidence    INTEGER,
    certainty     TEXT,
    risk          TEXT,
    engine        TEXT,
    model_version TEXT,
    runtime       TEXT,
    frames        INTEGER,
    suspicious    INTEGER,
    -- How many faces were in the picture, and whether there were any at
    -- all. Both were silently absent until a group photo with one swapped
    -- face turned out to be decided by whichever head was widest; how
    -- often real uploads have more than one face is now measurable rather
    -- than assumed.
    faces         INTEGER,
    face_found    BOOLEAN,
    latency_ms    INTEGER
);
CREATE INDEX IF NOT EXISTS analyses_scan_id ON analyses (scan_id);
CREATE INDEX IF NOT EXISTS analyses_at      ON analyses (at DESC);

CREATE TABLE IF NOT EXISTS feedback (
    id            BIGSERIAL PRIMARY KEY,
    at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    scan_id       TEXT,
    prediction    TEXT,
    confidence    INTEGER,
    file_type     TEXT,
    agree         BOOLEAN NOT NULL,
    note          TEXT
);
CREATE INDEX IF NOT EXISTS feedback_scan_id ON feedback (scan_id);
CREATE INDEX IF NOT EXISTS feedback_agree   ON feedback (agree);

-- Columns added after a table already existed somewhere. CREATE TABLE IF
-- NOT EXISTS silently does nothing to a live table, so without these every
-- insert would fail on the missing column - and because this module
-- swallows its own errors by design, analytics would simply stop recording
-- with nothing in the logs anyone was watching. Additive only: no column is
-- ever dropped or retyped here.
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS faces      INTEGER;
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS face_found BOOLEAN;
"""


def ensure_schema(force=False):
    """Create the tables once per process. Safe to call repeatedly."""
    global _schema_ready
    if not enabled():
        return False
    with _lock:
        if _schema_ready and not force:
            return True
        try:
            with _connect() as conn, conn.cursor() as cur:
                cur.execute(SCHEMA)
                conn.commit()
            _schema_ready = True
            log.info("analytics schema ready (postgres)")
            return True
        except Exception as exc:
            log.warning("analytics schema unavailable: %s: %s",
                        type(exc).__name__, exc)
            return False


# ------------------------------------------------------------------ writing

def _insert(table, row):
    """One row, best effort. Called on a background thread."""
    try:
        if not ensure_schema():
            return
        columns = ", ".join(row)
        holders = ", ".join(["%s"] * len(row))
        with _connect() as conn, conn.cursor() as cur:
            cur.execute(f"INSERT INTO {table} ({columns}) VALUES ({holders})",
                        list(row.values()))
            conn.commit()
    except Exception as exc:
        # Deliberately swallowed. A verdict the user already has must not be
        # undone by a bookkeeping failure.
        log.warning("analytics write failed (%s): %s: %s",
                    table, type(exc).__name__, exc)


def _write_async(table, row):
    """Off the request thread, so a slow or sleeping database never shows up
    as latency on someone's analysis."""
    threading.Thread(target=_insert, args=(table, row), daemon=True).start()


def _append_jsonl(path, entry):
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
    except Exception as exc:
        log.warning("could not append %s: %s", path, exc)


def _extension_of(file_name):
    """The extension, never the name. `passport.jpg` -> `.jpg`."""
    ext = os.path.splitext(str(file_name or ""))[1].lower()
    return ext[:8] if ext.startswith(".") else ""


def record_analysis(*, scan_id, file_name, file_type, file_bytes, result,
                    identity, latency_ms, engine):
    """One verdict. No media, no filename — see the module docstring."""
    if not CFG.ANALYTICS:
        return

    video = result.get("video") or {}
    row = {
        "scan_id": str(scan_id or "")[:64],
        "file_type": str(file_type or "")[:10],
        "file_ext": _extension_of(file_name),
        "file_bytes": int(file_bytes or 0),
        "prediction": str(result.get("prediction") or "")[:20],
        "confidence": int(result.get("confidence") or 0),
        "certainty": str(result.get("certainty") or "")[:20],
        "risk": str(result.get("risk") or "")[:10],
        "engine": str(engine or "")[:12],
        "model_version": str(identity.get("version") or "")[:32],
        "runtime": str(identity.get("runtime") or "")[:16],
        "frames": int(result.get("framesAnalyzed") or 0),
        "suspicious": int(video.get("suspiciousFrames") or 0),
        # -1 rather than 0 when the field is absent, so an old row and a
        # picture with genuinely no face stay distinguishable.
        "faces": int(result["facesFound"]) if "facesFound" in result else -1,
        # Was a face found - asked of the detector rather than inferred from
        # whether the explanation produced any regions, which is what this
        # did before the engine reported it. Explain is best-effort and can
        # fail for reasons that have nothing to do with faces, so that proxy
        # recorded "no face" for images that plainly had one.
        "face_found": bool(result["faceFound"]) if "faceFound" in result else None,
        "latency_ms": int(latency_ms or 0),
    }

    if enabled():
        _write_async("analyses", row)


def record_feedback(entry):
    """A human saying the verdict was right or wrong.

    This is the row that matters. A disagreement is a candidate mislabel,
    and a run of them on real photographs is the labelled set this project
    has never had. It is an evaluation signal and never a training label —
    nothing here reaches the model automatically."""
    if not CFG.ANALYTICS:
        return

    _append_jsonl(CFG.FEEDBACK_PATH, {**entry, "at": _now()})

    if enabled():
        _write_async("feedback", {
            "scan_id": str(entry.get("scanId") or "")[:64],
            "prediction": str(entry.get("prediction") or "")[:20],
            "confidence": int(entry.get("confidence") or 0),
            "file_type": str(entry.get("fileType") or "")[:10],
            "agree": bool(entry.get("agree")),
            "note": str(entry.get("note") or "")[:280] or None,
        })


def _now():
    return datetime.now(timezone.utc).isoformat()


# ------------------------------------------------------------------ reading

def summary(limit_days=30):
    """What the collected data says. Aggregates only — no rows come back.

    The disagreement figures are the point: they are the closest thing this
    project has to labelled real-world data."""
    if not enabled():
        return {"backend": backend_name(), "available": False}

    queries = {
        "analyses": "SELECT count(*) FROM analyses WHERE at > now() - %s::interval",
        "feedback": "SELECT count(*) FROM feedback  WHERE at > now() - %s::interval",
        "disagreements": ("SELECT count(*) FROM feedback "
                          "WHERE agree = false AND at > now() - %s::interval"),
    }
    window = f"{int(limit_days)} days"

    out = {"backend": backend_name(), "available": True, "window_days": limit_days}
    try:
        with _connect() as conn, conn.cursor() as cur:
            for key, sql in queries.items():
                cur.execute(sql, (window,))
                out[key] = int(cur.fetchone()[0])

            cur.execute(
                "SELECT prediction, count(*) FROM analyses "
                "WHERE at > now() - %s::interval GROUP BY prediction", (window,))
            out["by_prediction"] = {r[0] or "?": int(r[1]) for r in cur.fetchall()}

            cur.execute(
                "SELECT file_type, count(*) FROM analyses "
                "WHERE at > now() - %s::interval GROUP BY file_type", (window,))
            out["by_file_type"] = {r[0] or "?": int(r[1]) for r in cur.fetchall()}

            cur.execute(
                "SELECT round(avg(latency_ms)), max(latency_ms) FROM analyses "
                "WHERE at > now() - %s::interval", (window,))
            row = cur.fetchone()
            out["latency_ms"] = {"mean": int(row[0] or 0), "max": int(row[1] or 0)}

            # The rows worth looking at by hand.
            cur.execute(
                "SELECT f.scan_id, f.prediction, f.confidence, f.file_type, f.at "
                "FROM feedback f WHERE f.agree = false "
                "ORDER BY f.at DESC LIMIT 20")
            out["recent_disagreements"] = [
                {"scan_id": r[0], "prediction": r[1], "confidence": r[2],
                 "file_type": r[3], "at": r[4].isoformat() if r[4] else None}
                for r in cur.fetchall()]

        if out["feedback"]:
            out["disagreement_rate"] = round(
                out["disagreements"] / out["feedback"], 4)
    except Exception as exc:
        log.warning("analytics summary failed: %s: %s", type(exc).__name__, exc)
        return {"backend": backend_name(), "available": False,
                "error": type(exc).__name__}
    return out